"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./mymc.py']
DATA_FILES = []
OPTIONS = {'includes': './gui.py,./guires.py,./lzari.py,./ps2mc_dir.py,./ps2mc_ecc.py,./ps2mc.py,./ps2save.py,./round.py,./sjistab.py,./verbuild.py',
 'resources': './mymc.icns',
 'iconfile': './mymc.icns',
 'optimize': True,
 'plist': dict(
 	NSRequiresAquaSystemAppearance=False,
 	NSHumanReadableCopyright="Public Domain - Ross Ridge, 2004",
    CFBundleShortVersionString="2.6"
 )
 }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
